#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add($command = new \FDTool\GitChecker\Command\GitCleanCommand());
$application->setDefaultCommand($command->getName(), true);

$application->run();
